// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 11.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeFactory.CodeGeneration.Templates.Database
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public partial class Database : DatabaseBase
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n");
            
            #line 7 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
 foreach(var kvp in config.EntitiesBySchema){ 
            
            #line default
            #line hidden
            this.Write("\r\nCREATE SCHEMA [");
            
            #line 9 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(kvp.Key));
            
            #line default
            #line hidden
            this.Write("]\r\nGO\r\n\r\n");
            
            #line 12 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 14 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
 foreach(var entity in config.Entities){ 
            
            #line default
            #line hidden
            this.Write("\r\nCREATE TABLE [");
            
            #line 16 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 16 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("](\r\n\t");
            
            #line 17 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
 foreach(var field in entity.Fields){ 
            
            #line default
            #line hidden
            this.Write("\t[");
            
            #line 18 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write("] ");
            
            #line 18 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.SqlType));
            
            #line default
            #line hidden
            this.Write(",\r\n\t");
            
            #line 19 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
}
            
            #line default
            #line hidden
            this.Write(")\r\nGO\r\nALTER TABLE [");
            
            #line 22 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 22 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("] ADD CONSTRAINT PK_");
            
            #line 22 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 22 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write(" PRIMARY KEY NONCLUSTERED([");
            
            #line 22 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.KeyField));
            
            #line default
            #line hidden
            this.Write("]) \r\nGO\r\n\r\n");
            
            #line 25 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
 foreach(var tabularSection in entity.TabularSections){ 
            
            #line default
            #line hidden
            this.Write("\r\nCREATE TABLE [");
            
            #line 27 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 27 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 27 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.Name));
            
            #line default
            #line hidden
            this.Write("](\r\n\t");
            
            #line 28 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
 foreach(var field in tabularSection.Fields){ 
            
            #line default
            #line hidden
            this.Write("\t[");
            
            #line 29 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write("] ");
            
            #line 29 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.SqlType));
            
            #line default
            #line hidden
            this.Write(",\r\n\t");
            
            #line 30 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
}
            
            #line default
            #line hidden
            this.Write(")\r\nGO\r\nALTER TABLE [");
            
            #line 33 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 33 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 33 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.Name));
            
            #line default
            #line hidden
            this.Write("] ADD CONSTRAINT PK_");
            
            #line 33 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 33 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 33 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.Name));
            
            #line default
            #line hidden
            this.Write(" PRIMARY KEY NONCLUSTERED([");
            
            #line 33 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.KeyField));
            
            #line default
            #line hidden
            this.Write("]) \r\nALTER TABLE [");
            
            #line 34 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 34 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 34 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.Name));
            
            #line default
            #line hidden
            this.Write("] ADD CONSTRAINT FK_");
            
            #line 34 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 34 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 34 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 34 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 34 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_EntityId FOREIGN KEY ([Ref]) REFERENCES [");
            
            #line 34 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 34 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("]([Id]) ON DELETE CASCADE\r\n");
            
            #line 35 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
 if(tabularSection.HasTabularSectionKey){ 
            
            #line default
            #line hidden
            this.Write("ALTER TABLE [");
            
            #line 36 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 36 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 36 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.Name));
            
            #line default
            #line hidden
            this.Write("] ADD CONSTRAINT UQ_");
            
            #line 36 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 36 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 36 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.Name));
            
            #line default
            #line hidden
            this.Write("_Key UNIQUE ([Ref]");
            
            #line 36 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
 foreach(var field in tabularSection.TabularSectionKeys){ 
            
            #line default
            #line hidden
            this.Write(",[");
            
            #line 36 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write("]");
            
            #line 36 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
}
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 37 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
}
            
            #line default
            #line hidden
            this.Write("GO\r\n\r\nCREATE TYPE [");
            
            #line 40 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("].[T_");
            
            #line 40 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 40 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.Name));
            
            #line default
            #line hidden
            this.Write("] AS TABLE\r\n(\r\n");
            
            #line 42 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
 foreach(var field in tabularSection.TabularFieldsExceptRefAndKey){ 
            
            #line default
            #line hidden
            this.Write("[");
            
            #line 43 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write("] ");
            
            #line 43 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.SqlTypeShort));
            
            #line default
            #line hidden
            
            #line 43 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
 if(!tabularSection.LastField(field.Name)){ 
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 43 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
}
            
            #line default
            #line hidden
            
            #line 44 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
}
            
            #line default
            #line hidden
            
            #line 45 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
 if(tabularSection.HasTabularSectionKey){ 
            
            #line default
            #line hidden
            this.Write(" \r\nUNIQUE(");
            
            #line 47 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
 foreach(var field in tabularSection.TabularSectionKeys){ 
            
            #line default
            #line hidden
            this.Write("[");
            
            #line 47 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write("]");
            
            #line 47 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
 if(!tabularSection.LastTabularSectionKey(field.Name)){ 
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 47 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
}
            
            #line default
            #line hidden
            
            #line 47 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
}
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 48 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
}
            
            #line default
            #line hidden
            this.Write(")\r\nGO\r\n\r\n");
            
            #line 52 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 54 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 56 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
 foreach(var entity in config.Entities){ 
            
            #line default
            #line hidden
            
            #line 57 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
 foreach(var field in entity.Fields){ 
            
            #line default
            #line hidden
            
            #line 58 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
 if(!field.SimpleType){ 
            
            #line default
            #line hidden
            this.Write("ALTER TABLE [");
            
            #line 59 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 59 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("] ADD CONSTRAINT FK_");
            
            #line 59 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 59 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 59 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.SqlLinkedSchema));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 59 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.SqlLinkedTable));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 59 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write(" FOREIGN KEY ([");
            
            #line 59 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write("]) REFERENCES [");
            
            #line 59 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.SqlLinkedSchema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 59 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.SqlLinkedTable));
            
            #line default
            #line hidden
            this.Write("]([Id])\r\n");
            
            #line 60 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
}
            
            #line default
            #line hidden
            
            #line 61 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
 if(field.Unique){ 
            
            #line default
            #line hidden
            this.Write("ALTER TABLE [");
            
            #line 62 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 62 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("] ADD CONSTRAINT UQ_");
            
            #line 62 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 62 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 62 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write(" UNIQUE ([");
            
            #line 62 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write("])\r\n");
            
            #line 63 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
}
            
            #line default
            #line hidden
            
            #line 64 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
}
            
            #line default
            #line hidden
            this.Write("GO\r\n\r\n");
            
            #line 67 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
 foreach(var tabularSection in entity.TabularSections){ 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 69 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
 foreach(var field in tabularSection.Fields){ 
            
            #line default
            #line hidden
            
            #line 70 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
 if(!field.SimpleType){ 
            
            #line default
            #line hidden
            this.Write("ALTER TABLE [");
            
            #line 71 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 71 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 71 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.Name));
            
            #line default
            #line hidden
            this.Write("] ADD CONSTRAINT FK_");
            
            #line 71 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 71 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("__");
            
            #line 71 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 71 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.SqlLinkedSchema));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 71 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.SqlLinkedTable));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 71 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write(" FOREIGN KEY ([");
            
            #line 71 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write("]) REFERENCES [");
            
            #line 71 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.SqlLinkedSchema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 71 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.SqlLinkedTable));
            
            #line default
            #line hidden
            this.Write("]([Id])\r\n");
            
            #line 72 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
}
            
            #line default
            #line hidden
            
            #line 73 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
}
            
            #line default
            #line hidden
            this.Write("GO\r\n\r\n");
            
            #line 76 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 78 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Database.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public class DatabaseBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
