// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 11.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeFactory.CodeGeneration.Templates.Database
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public partial class Filters : FiltersBase
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"
CREATE TABLE [admin].FiltersInfo([CreationTime] DATETIME, Anchor NTEXT, Scope VARCHAR(200), UserId UNIQUEIDENTIFIER)
GO
ALTER TABLE [admin].FiltersInfo ADD CONSTRAINT UQ_Admin_FiltersInfo UNIQUE NONCLUSTERED([CreationTime],[Scope])
GO

---------------------------------------------------------FILTER TABLES-------------------------------------------------------

");
            
            #line 14 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
 foreach(var entity in config.Entities){ 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 16 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
 if(entity.SyncFilterIsComplicated){ 
            
            #line default
            #line hidden
            this.Write("CREATE TABLE [");
            
            #line 17 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 17 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_filterids](\r\n\t[ScopeId] INT NOT NULL,\r\n\t[Id] UNIQUEIDENTIFIER NOT NULL,\r\n\t[IsNew" +
                    "] INT NOT NULL\r\n)\r\nGO\r\nALTER TABLE [");
            
            #line 23 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 23 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_filterids] ADD CONSTRAINT UQ_");
            
            #line 23 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 23 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_filterids UNIQUE([ScopeId],[Id],[IsNew])\r\nGO\r\n\r\nCREATE PROCEDURE [");
            
            #line 26 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 26 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write(@"_adm_getfilterids] @UserId UNIQUEIDENTIFIER
AS
DECLARE @ScopeId INT
SELECT TOP 1 @ScopeId = si.scope_local_id
FROM [admin].FiltersInfo fi
JOIN [dbo].scope_info si on si.[sync_scope_name] = fi.scope
WHERE fi.UserId = @UserId
ORDER BY fi.CreationTime DESC

SELECT [base].[Id] 
FROM [");
            
            #line 36 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 36 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("] [base]\r\nJOIN [");
            
            #line 37 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 37 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_filterids] T ON T.Id = [base].[");
            
            #line 37 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.SyncFilterColumn));
            
            #line default
            #line hidden
            this.Write("]\r\nWHERE T.ScopeId = @ScopeId AND T.IsNew < 2\r\nOPTION (OPTIMIZE FOR(@ScopeId UNKN" +
                    "OWN))\r\nGO\r\n\r\n");
            
            #line 42 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 44 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
 foreach(var tabularSection in entity.TabularSections){ 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 46 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
 if(tabularSection.SyncFilterIsComplicated){ 
            
            #line default
            #line hidden
            this.Write("CREATE TABLE [");
            
            #line 47 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 47 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 47 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.Name));
            
            #line default
            #line hidden
            this.Write("_filterids](\r\n\t[ScopeId] INT NOT NULL,\r\n\t[Id] UNIQUEIDENTIFIER NOT NULL,\r\n\t[IsNew" +
                    "] INT NOT NULL\r\n)\r\nGO\r\nALTER TABLE [");
            
            #line 53 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 53 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 53 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.Name));
            
            #line default
            #line hidden
            this.Write("_filterids] ADD CONSTRAINT UQ_");
            
            #line 53 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 53 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 53 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.Name));
            
            #line default
            #line hidden
            this.Write("_filterids UNIQUE([ScopeId],[Id],[IsNew])\r\nGO\r\n");
            
            #line 55 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 57 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
}
            
            #line default
            #line hidden
            
            #line 58 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n---------------------------------------------------------UPDATE FILTER PROC----" +
                    "---------------------------------------------------\r\n\r\n");
            
            #line 62 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
 foreach(var entity in config.Entities){ 
            
            #line default
            #line hidden
            
            #line 63 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
 if(entity.SyncFilterIsComplicatedEx){ 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 65 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
 if(entity.SyncFilterIsComplicated){ 
            
            #line default
            #line hidden
            this.Write("ALTER TABLE [");
            
            #line 66 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 66 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_filterids] ADD CONSTRAINT FK_");
            
            #line 66 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 66 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_filterids FOREIGN KEY([Id]) REFERENCES [");
            
            #line 66 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.SyncFilterField.SqlLinkedSchema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 66 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.SyncFilterField.SqlLinkedTable));
            
            #line default
            #line hidden
            this.Write("]([Id])\r\nGO\r\n");
            
            #line 68 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 70 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
 foreach(var tabularSection in entity.TabularSections){ 
            
            #line default
            #line hidden
            
            #line 71 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
 if(tabularSection.SyncFilterIsComplicated){ 
            
            #line default
            #line hidden
            this.Write("ALTER TABLE [");
            
            #line 72 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 72 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 72 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.Name));
            
            #line default
            #line hidden
            this.Write("_filterids] ADD CONSTRAINT FK_");
            
            #line 72 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 72 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 72 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.Name));
            
            #line default
            #line hidden
            this.Write("_filterids FOREIGN KEY([Id]) REFERENCES [");
            
            #line 72 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.SyncFilterField.SqlLinkedSchema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 72 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.SyncFilterField.SqlLinkedTable));
            
            #line default
            #line hidden
            this.Write("]([Id])\r\nGO\r\n");
            
            #line 74 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
}
            
            #line default
            #line hidden
            
            #line 75 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 77 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
}
            
            #line default
            #line hidden
            
            #line 78 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 80 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
 foreach(var entity in config.Entities){ 
            
            #line default
            #line hidden
            
            #line 81 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
 if(entity.SyncFilterIsComplicatedEx){ 
            
            #line default
            #line hidden
            this.Write("\r\nCREATE PROCEDURE [");
            
            #line 83 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 83 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_updatefilters] @ScopeId INT, @FirstSync BIT, @SameAnchor BIT, @UserId UNIQUEIDEN" +
                    "TIFIER\r\nAS\r\nSET NOCOUNT ON\r\nIF @FirstSync = 1\r\nBEGIN\r\n");
            
            #line 88 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
 if(entity.SyncFilterIsComplicated){ 
            
            #line default
            #line hidden
            this.Write("DELETE FROM [");
            
            #line 89 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 89 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_filterids] WHERE ScopeId = @ScopeId\r\nINSERT INTO [");
            
            #line 90 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 90 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_filterids]([ScopeId],[Id],[IsNew])\r\nSELECT DISTINCT @ScopeId, [");
            
            #line 91 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.SyncFilterColumn));
            
            #line default
            #line hidden
            this.Write("], 0\r\nFROM [");
            
            #line 92 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 92 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("] T\r\nWHERE ");
            
            #line 93 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.SyncFilter2));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 94 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
}
            
            #line default
            #line hidden
            
            #line 95 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
 foreach(var tabularSection in entity.TabularSections){ 
            
            #line default
            #line hidden
            
            #line 96 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
 if(tabularSection.SyncFilterIsComplicated){ 
            
            #line default
            #line hidden
            this.Write("DELETE FROM [");
            
            #line 97 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 97 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 97 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.Name));
            
            #line default
            #line hidden
            this.Write("_filterids] WHERE ScopeId = @ScopeId\r\nINSERT INTO [");
            
            #line 98 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 98 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 98 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.Name));
            
            #line default
            #line hidden
            this.Write("_filterids]([ScopeId],[Id],[IsNew])\r\nSELECT DISTINCT @ScopeId, [");
            
            #line 99 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.SyncFilterColumn));
            
            #line default
            #line hidden
            this.Write("], 0 \r\nFROM [");
            
            #line 100 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 100 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 100 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.Name));
            
            #line default
            #line hidden
            this.Write("] T\r\nWHERE ");
            
            #line 101 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.SyncFilter2));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 102 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
}
            
            #line default
            #line hidden
            
            #line 103 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
}
            
            #line default
            #line hidden
            this.Write("END\r\nELSE\r\nBEGIN\r\n\t");
            
            #line 107 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
 if(entity.SyncFilterIsComplicated){ 
            
            #line default
            #line hidden
            this.Write("\tIF @SameAnchor = 0\r\n\tBEGIN\r\n\t\tUPDATE [");
            
            #line 110 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 110 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_filterids] SET IsNew = 0 WHERE ScopeId = @ScopeId AND IsNew = 1\r\n\t\tDELETE FROM [" +
                    "");
            
            #line 111 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 111 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_filterids] WHERE ScopeId = @ScopeId AND IsNew = 2\r\n\tEND\r\n\r\n\tDECLARE @");
            
            #line 114 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 114 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write(" TABLE([");
            
            #line 114 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.SyncFilterColumn));
            
            #line default
            #line hidden
            this.Write("] UNIQUEIDENTIFIER)\r\n\tINSERT @");
            
            #line 115 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 115 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\tSELECT DISTINCT [");
            
            #line 116 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.SyncFilterColumn));
            
            #line default
            #line hidden
            this.Write("] FROM [");
            
            #line 116 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 116 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("] T\r\n\tWHERE ");
            
            #line 117 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.SyncFilter2));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n\tINSERT INTO [");
            
            #line 119 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 119 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_filterids]([ScopeId],[Id], [IsNew])\r\n\tSELECT @ScopeId, T.[");
            
            #line 120 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.SyncFilterColumn));
            
            #line default
            #line hidden
            this.Write("], 1\r\n\tFROM @");
            
            #line 121 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 121 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write(" T\r\n\tLEFT JOIN [");
            
            #line 122 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 122 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_filterids] T2 ON T2.Id = T.[");
            
            #line 122 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.SyncFilterColumn));
            
            #line default
            #line hidden
            this.Write("] AND T2.ScopeId = @ScopeId\r\n\tWHERE T2.Id IS NULL\r\n\tOPTION (OPTIMIZE FOR(@ScopeId" +
                    " UNKNOWN))\r\n\r\n\tUPDATE [");
            
            #line 126 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 126 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_filterids] SET [IsNew] = 2\r\n\tFROM [");
            
            #line 127 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 127 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_filterids] T2\r\n\tLEFT JOIN @");
            
            #line 128 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 128 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write(" T ON T2.[Id] =  T.[");
            
            #line 128 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.SyncFilterColumn));
            
            #line default
            #line hidden
            this.Write("] AND T2.ScopeId = @ScopeId\r\n\tWHERE T.[");
            
            #line 129 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.SyncFilterColumn));
            
            #line default
            #line hidden
            this.Write("] IS NULL AND T2.ScopeId = @ScopeId\r\n\tOPTION (OPTIMIZE FOR(@ScopeId UNKNOWN))\r\n\r\n" +
                    "\t");
            
            #line 132 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
}
            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 133 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
 foreach(var tabularSection in entity.TabularSections){ 
            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 134 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
 if(tabularSection.SyncFilterIsComplicated){ 
            
            #line default
            #line hidden
            this.Write("\r\n\tIF @SameAnchor = 0\r\n\tBEGIN\r\n\t\tUPDATE [");
            
            #line 138 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 138 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 138 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.Name));
            
            #line default
            #line hidden
            this.Write("_filterids] SET IsNew = 0 WHERE ScopeId = @ScopeId AND IsNew = 1\r\n\t\tDELETE FROM [" +
                    "");
            
            #line 139 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 139 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 139 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.Name));
            
            #line default
            #line hidden
            this.Write("_filterids] WHERE ScopeId = @ScopeId AND IsNew = 2\r\n\tEND\r\n\r\n\tDECLARE @");
            
            #line 142 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 142 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 142 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.Name));
            
            #line default
            #line hidden
            this.Write(" TABLE([");
            
            #line 142 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.SyncFilterColumn));
            
            #line default
            #line hidden
            this.Write("] UNIQUEIDENTIFIER)\r\n\tINSERT @");
            
            #line 143 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 143 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 143 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\tSELECT DISTINCT [");
            
            #line 144 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.SyncFilterColumn));
            
            #line default
            #line hidden
            this.Write("] FROM [");
            
            #line 144 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 144 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 144 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.Name));
            
            #line default
            #line hidden
            this.Write("] T\r\n\tWHERE ");
            
            #line 145 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.SyncFilter2));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n\tINSERT INTO [");
            
            #line 147 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 147 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 147 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.Name));
            
            #line default
            #line hidden
            this.Write("_filterids]([ScopeId],[Id], [IsNew])\r\n\tSELECT @ScopeId, T.[");
            
            #line 148 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.SyncFilterColumn));
            
            #line default
            #line hidden
            this.Write("], 1\r\n\tFROM @");
            
            #line 149 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 149 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 149 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.Name));
            
            #line default
            #line hidden
            this.Write(" T\r\n\tLEFT JOIN [");
            
            #line 150 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 150 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 150 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.Name));
            
            #line default
            #line hidden
            this.Write("_filterids] T2 ON T2.Id = T.[");
            
            #line 150 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.SyncFilterColumn));
            
            #line default
            #line hidden
            this.Write("] AND T2.ScopeId = @ScopeId\r\n\tWHERE T2.Id IS NULL\r\n\tOPTION (OPTIMIZE FOR(@ScopeId" +
                    " UNKNOWN))\r\n\r\n\tUPDATE [");
            
            #line 154 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 154 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 154 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.Name));
            
            #line default
            #line hidden
            this.Write("_filterids] SET [IsNew] = 2\r\n\tFROM [");
            
            #line 155 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 155 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 155 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.Name));
            
            #line default
            #line hidden
            this.Write("_filterids] T2\r\n\tLEFT JOIN @");
            
            #line 156 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 156 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 156 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.Name));
            
            #line default
            #line hidden
            this.Write(" T ON T2.[Id] =  T.[");
            
            #line 156 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.SyncFilterColumn));
            
            #line default
            #line hidden
            this.Write("] AND T2.ScopeId = @ScopeId\r\n\tWHERE T.[");
            
            #line 157 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.SyncFilterColumn));
            
            #line default
            #line hidden
            this.Write("] IS NULL AND T2.ScopeId = @ScopeId\r\n\tOPTION (OPTIMIZE FOR(@ScopeId UNKNOWN))\r\n\r\n" +
                    "\t");
            
            #line 160 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
}
            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 161 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
}
            
            #line default
            #line hidden
            this.Write("END\r\nGO\r\n");
            
            #line 164 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
}
            
            #line default
            #line hidden
            
            #line 165 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
}
            
            #line default
            #line hidden
            this.Write(@"
CREATE PROCEDURE [admin].BeforeSyncSession @anchor NTEXT, @scope VARCHAR(200), @UserId UNIQUEIDENTIFIER
AS
SET NOCOUNT ON
DECLARE @ScopeId INT
SELECT @ScopeId = scope_local_id FROM dbo.scope_info WHERE sync_scope_name = @scope
IF @ScopeId IS NULL
BEGIN
	RAISERROR('Scope ""%s"" not found', 16, 1, @scope)
	RETURN
END

DECLARE @FirstSync BIT
DECLARE @SameAnchor BIT
SET @FirstSync = 1
SET @SameAnchor = 1
IF DATALENGTH(@anchor) <> 0
BEGIN
	SET @FirstSync = 0
    DECLARE @lastAnchor VARCHAR(MAX)
	SELECT @lastAnchor = CONVERT(VARCHAR(MAX), Anchor) FROM [admin].FiltersInfo WHERE Scope = @scope AND CreationTime = (SELECT MAX(CreationTime) FROM [admin].FiltersInfo WHERE Scope = @scope)
	IF CONVERT(VARCHAR(MAX), @anchor) <> @lastAnchor
		SET @SameAnchor = 0
END

");
            
            #line 191 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
 foreach(var entity in config.Entities){ 
            
            #line default
            #line hidden
            
            #line 192 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
 if(entity.SyncFilterIsComplicatedEx){ 
            
            #line default
            #line hidden
            this.Write("EXEC [");
            
            #line 193 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 193 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_updatefilters] @ScopeId, @FirstSync, @SameAnchor, @UserId\r\n");
            
            #line 194 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
}
            
            #line default
            #line hidden
            
            #line 195 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
}
            
            #line default
            #line hidden
            this.Write("INSERT INTO [admin].FiltersInfo([CreationTime], [Anchor], [Scope], [UserId]) SELE" +
                    "CT GETDATE(), @anchor, @scope, @UserId\r\nGO\r\n\r\n\r\nCREATE PROCEDURE [admin].RemoveF" +
                    "ilters\r\nAS\r\nBEGIN\r\n");
            
            #line 203 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
 foreach(var entity in config.Entities){ 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 205 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
 if(entity.SyncFilterIsComplicated){ 
            
            #line default
            #line hidden
            this.Write("ALTER TABLE [");
            
            #line 206 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 206 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_filterids] DROP CONSTRAINT UQ_");
            
            #line 206 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 206 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_filterids\r\nDROP TABLE [");
            
            #line 207 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 207 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_filterids]\r\n");
            
            #line 208 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 210 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
 foreach(var tabularSection in entity.TabularSections){ 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 212 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
 if(tabularSection.SyncFilterIsComplicated){ 
            
            #line default
            #line hidden
            this.Write("ALTER TABLE [");
            
            #line 213 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 213 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 213 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.Name));
            
            #line default
            #line hidden
            this.Write("_filterids] DROP CONSTRAINT UQ_");
            
            #line 213 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 213 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 213 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.Name));
            
            #line default
            #line hidden
            this.Write("_filterids\r\nDROP TABLE [");
            
            #line 214 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 214 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 214 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.Name));
            
            #line default
            #line hidden
            this.Write("_filterids]\r\n");
            
            #line 215 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 217 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
}
            
            #line default
            #line hidden
            
            #line 218 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 220 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
 foreach(var entity in config.Entities){ 
            
            #line default
            #line hidden
            
            #line 221 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
 if(entity.SyncFilterIsComplicatedEx){ 
            
            #line default
            #line hidden
            this.Write("DROP PROCEDURE [");
            
            #line 222 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("].[");
            
            #line 222 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_updatefilters]\r\n");
            
            #line 223 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
}
            
            #line default
            #line hidden
            
            #line 224 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Database\Filters.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\nDROP TABLE [admin].FiltersInfo\r\nDROP PROCEDURE [admin].BeforeSyncSession\r\nDROP " +
                    "PROCEDURE [admin].RemoveFilters\r\n\r\nEND\r\nGO\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public class FiltersBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
