// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 11.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeFactory.CodeGeneration.Templates.Code
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public partial class Client : ClientBase
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"using System;

namespace DefaultScope
{
	public static class ContextFactory
	{
		public static Microsoft.Synchronization.ClientServices.IsolatedStorage.IsolatedStorageOfflineContext CreateContext(string cachePath, System.Uri serviceUri)
		{
			return new ");
            
            #line 14 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(config.ServerScope));
            
            #line default
            #line hidden
            this.Write(".OfflineContext(cachePath, serviceUri);\r\n\t\t}\r\n\r\n\t\tpublic static String ScopeName\r" +
                    "\n\t\t{\r\n\t\t\tget\r\n\t\t\t{\r\n\t\t\t\treturn \"");
            
            #line 21 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(config.ServerScope));
            
            #line default
            #line hidden
            this.Write("\";\r\n\t\t\t}\r\n\t\t}\r\n\r\n\t\tpublic static String ConfigName\r\n\t\t{\r\n\t\t\tget\r\n\t\t\t{\r\n\t\t\t\treturn" +
                    " \"");
            
            #line 29 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(config.ConfigVersion.Name));
            
            #line default
            #line hidden
            this.Write("\";\r\n\t\t\t}\r\n\t\t}\r\n\r\n\t\tpublic static String Version\r\n\t\t{\r\n\t\t\tget\r\n\t\t\t{\r\n\t\t\t\treturn \"");
            
            #line 37 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(config.ConfigVersion.Version));
            
            #line default
            #line hidden
            this.Write("\";\r\n\t\t\t}\r\n\t\t}\r\n\t\t\r\n\t}\r\n}\r\n\r\nnamespace ");
            
            #line 44 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(config.ServerScope));
            
            #line default
            #line hidden
            this.Write(" \r\n{\r\n\t");
            
            #line 46 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
 foreach(var kvp in config.EntitiesBySchema){ 
            
            #line default
            #line hidden
            this.Write(" \r\n\tnamespace ");
            
            #line 47 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(kvp.Key));
            
            #line default
            #line hidden
            this.Write(" \r\n\t{\r\n\t\t");
            
            #line 49 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
 foreach(var entity in kvp.Value){ 
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\r\n\t\t[System.Serializable]\r\n\t\t[BitMobile.DbEngine.TableAttribute]\r\n\t\tpublic p" +
                    "artial class ");
            
            #line 53 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write(" : Microsoft.Synchronization.ClientServices.IsolatedStorage.IsolatedStorageOfflin" +
                    "eEntity \r\n\t\t{\r\n\t\t\t");
            
            #line 55 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
 foreach(var field in entity.Fields){ 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\tprivate ");
            
            #line 57 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.DataType));
            
            #line default
            #line hidden
            this.Write(" _");
            
            #line 57 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write(";\t\t\t\t    \r\n\r\n\t\t\t");
            
            #line 59 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
 if(!field.SimpleType || field.KeyField){ 
            
            #line default
            #line hidden
            this.Write("\t\t\tpublic ");
            
            #line 60 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.DataType));
            
            #line default
            #line hidden
            this.Write(" __");
            
            #line 60 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t{\r\n\t\t\t\tget \r\n\t\t\t\t{\r\n\t\t\t\t\treturn _");
            
            #line 64 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t\t}\r\n\t\t\t\tset\r\n\t\t\t\t{\r\n\t\t\t\t\t_");
            
            #line 68 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\t\t\t\t}\r\n\t\t\t}\r\n\t\t\t\r\n\t\t\t");
            
            #line 72 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
 if(field.KeyField){ 
            
            #line default
            #line hidden
            this.Write("\t\t\t[System.ComponentModel.DataAnnotations.KeyAttribute()]\r\n\t\t\t[BitMobile.DbEngine" +
                    ".PrimaryKeyAttribute]\r\n\t\t\t");
            
            #line 75 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t[BitMobile.DbEngine.ColumnAttribute]\r\n\t\t\tpublic BitMobile.DbEngine.DbRef ");
            
            #line 77 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t{\r\n\t\t\t\tget\r\n\t\t\t\t{\r\n\t\t\t\t\t");
            
            #line 81 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
 if(field.KeyField){ 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\treturn BitMobile.DbEngine.DbRef.CreateInstance(\"");
            
            #line 82 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(kvp.Key));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 82 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("\", _");
            
            #line 82 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\t\t\t");
            
            #line 83 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t");
            
            #line 84 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
 if(!field.KeyField){ 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\treturn BitMobile.DbEngine.DbRef.CreateInstance(\"");
            
            #line 85 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.SqlLinkedSchema));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 85 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.SqlLinkedTable));
            
            #line default
            #line hidden
            this.Write("\", _");
            
            #line 85 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\t\t\t");
            
            #line 86 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t\t}\r\n\t\t\t\tset\r\n\t\t\t\t{\r\n\t\t\t\t\tbase.OnPropertyChanging(\"");
            
            #line 90 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t\t\t_");
            
            #line 91 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write(" = value.Id;\r\n\t\t\t\t\tbase.OnPropertyChanged(\"");
            
            #line 92 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t\t}\r\n\t\t\t}\t\t\t\t\t\t\t\t\r\n\t\t\t");
            
            #line 95 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t");
            
            #line 97 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
 if(field.SimpleType && !field.KeyField){ 
            
            #line default
            #line hidden
            this.Write("\t\t\t[BitMobile.DbEngine.ColumnAttribute]\r\n\t\t\tpublic ");
            
            #line 99 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.DataType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 99 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t{\r\n\t\t\t\tget \r\n\t\t\t\t{\r\n\t\t\t\t\treturn _");
            
            #line 103 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t\t}\r\n\t\t\t\tset \r\n\t\t\t\t{\r\n\t\t\t\t\tbase.OnPropertyChanging(\"");
            
            #line 107 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write("\");\t\t\t\t\t\r\n\t\t\t\t\t_");
            
            #line 108 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\t\t\t\t\tbase.OnPropertyChanged(\"");
            
            #line 109 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t\t}\r\n\t\t\t}\r\n\t\t\t");
            
            #line 112 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t");
            
            #line 114 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\tpublic static ");
            
            #line 116 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write(" CreateInstance(OfflineContext dao)\r\n            {\r\n                ");
            
            #line 118 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write(" entity = new ");
            
            #line 118 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("();\r\n\t\t\t\t//entity.Init();\r\n                entity._Id = System.Guid.NewGuid();\r\n\t" +
                    "\t\t\tentity.SetIsNew();\r\n                //dao.AddItem<");
            
            #line 122 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write(">(entity);\r\n                return entity;\r\n            }\r\n\r\n\t\t\t");
            
            #line 126 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
 foreach(var tabularSection in entity.TabularSections){ 
            
            #line default
            #line hidden
            this.Write("\t\t\t\r\n\t\t\tpublic System.Collections.Generic.IEnumerable<");
            
            #line 128 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 128 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 128 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.Name));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 128 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.Name));
            
            #line default
            #line hidden
            this.Write("(OfflineContext context) \r\n\t\t\t{\r\n\t\t\t\tSystem.Collections.Generic.List<");
            
            #line 130 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 130 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 130 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.Name));
            
            #line default
            #line hidden
            this.Write("> result = new System.Collections.Generic.List<");
            
            #line 130 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 130 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 130 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.Name));
            
            #line default
            #line hidden
            this.Write(">();\r\n\t\t\t\tSystem.Collections.Generic.IEnumerable<");
            
            #line 131 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 131 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 131 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.Name));
            
            #line default
            #line hidden
            this.Write("> items = context.GetCollection<");
            
            #line 131 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 131 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 131 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.Name));
            
            #line default
            #line hidden
            this.Write(">();\r\n\t\t\t\tforeach(var item in items)\r\n\t\t\t\t{\r\n\t\t\t\t\tif(item.Ref.Equals(this.Id))\r\n\t" +
                    "\t\t\t\t\tresult.Add(item);\r\n\t\t\t\t}\r\n\t\t\t\treturn result;\r\n\t\t\t}\r\n\r\n\t\t\t");
            
            #line 140 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\r\n\t\t");
            
            #line 143 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
 foreach(var tabularSection in entity.TabularSections){ 
            
            #line default
            #line hidden
            this.Write(" \r\n\r\n\t\t[System.Serializable]\r\n\t\t[BitMobile.DbEngine.TableAttribute]\r\n\t\tpublic par" +
                    "tial class ");
            
            #line 147 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 147 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.Name));
            
            #line default
            #line hidden
            this.Write(" : Microsoft.Synchronization.ClientServices.IsolatedStorage.IsolatedStorageOfflin" +
                    "eEntity \r\n\t\t{\r\n\t\t\t");
            
            #line 149 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write(" _RefObject;\r\n\r\n\t\t\t");
            
            #line 151 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
 foreach(var field in tabularSection.Fields){ 
            
            #line default
            #line hidden
            this.Write("\t\t\t\r\n\t\t\tprivate ");
            
            #line 153 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.DataType));
            
            #line default
            #line hidden
            this.Write(" _");
            
            #line 153 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write(";\t\r\n\t\t\t\r\n\t\t\t");
            
            #line 155 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
 if(!field.SimpleType || (field.KeyField || field.RefField)){ 
            
            #line default
            #line hidden
            this.Write("\t\t\tpublic ");
            
            #line 156 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.DataType));
            
            #line default
            #line hidden
            this.Write(" __");
            
            #line 156 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t{\r\n\t\t\t\tget \r\n\t\t\t\t{\r\n\t\t\t\t\treturn _");
            
            #line 160 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t\t}\r\n\t\t\t\tset\r\n\t\t\t\t{\r\n\t\t\t\t\t_");
            
            #line 164 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\t\t\t\t}\r\n\t\t\t}\r\n\t\t\t\r\n\t\t\t");
            
            #line 168 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
 if(field.KeyField){ 
            
            #line default
            #line hidden
            this.Write("\t\t\t[System.ComponentModel.DataAnnotations.KeyAttribute()]\r\n\t\t\t[BitMobile.DbEngine" +
                    ".PrimaryKeyAttribute]\r\n\t\t\t");
            
            #line 171 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t[BitMobile.DbEngine.ColumnAttribute]\r\n\t\t\tpublic BitMobile.DbEngine.DbRef ");
            
            #line 173 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t{\r\n\t\t\t\tget\r\n\t\t\t\t{\r\n\t\t\t\t\t");
            
            #line 177 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
 if(field.KeyField){ 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\treturn BitMobile.DbEngine.DbRef.CreateInstance(\"");
            
            #line 178 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(kvp.Key));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 178 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 178 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.Name));
            
            #line default
            #line hidden
            this.Write("\", _");
            
            #line 178 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\t\t\t");
            
            #line 179 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t");
            
            #line 180 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
 if(field.RefField){ 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\treturn BitMobile.DbEngine.DbRef.CreateInstance(\"");
            
            #line 181 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(kvp.Key));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 181 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("\", _");
            
            #line 181 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\t\t\t");
            
            #line 182 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t");
            
            #line 183 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
 if(!field.KeyField && !field.RefField){ 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\treturn BitMobile.DbEngine.DbRef.CreateInstance(\"");
            
            #line 184 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.SqlLinkedSchema));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 184 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.SqlLinkedTable));
            
            #line default
            #line hidden
            this.Write("\", _");
            
            #line 184 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\t\t\t");
            
            #line 185 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t\t}\r\n\t\t\t\tset\r\n\t\t\t\t{\r\n\t\t\t\t\tbase.OnPropertyChanging(\"");
            
            #line 189 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t\t\t_");
            
            #line 190 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write(" = value.Id;\r\n\t\t\t\t\tbase.OnPropertyChanged(\"");
            
            #line 191 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t\t}\r\n\t\t\t}\t\t\t\t\t\t\t\t\r\n\t\t\t");
            
            #line 194 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t");
            
            #line 196 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
 if(field.SimpleType && !(field.KeyField || field.RefField)){ 
            
            #line default
            #line hidden
            this.Write("\t\t\t[BitMobile.DbEngine.ColumnAttribute]\r\n\t\t\tpublic ");
            
            #line 198 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.DataType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 198 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t{\r\n\t\t\t\tget \r\n\t\t\t\t{\r\n\t\t\t\t\treturn _");
            
            #line 202 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t\t}\r\n\t\t\t\tset \r\n\t\t\t\t{\r\n\t\t\t\t\tbase.OnPropertyChanging(\"");
            
            #line 206 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write("\");\t\t\t\t\t\r\n\t\t\t\t\t_");
            
            #line 207 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\t\t\t\t\tbase.OnPropertyChanged(\"");
            
            #line 208 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t\t}\r\n\t\t\t}\r\n\t\t\t");
            
            #line 211 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 212 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\tpublic static ");
            
            #line 214 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 214 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.Name));
            
            #line default
            #line hidden
            this.Write(" CreateInstance(OfflineContext dao)\r\n            {\r\n                ");
            
            #line 216 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 216 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.Name));
            
            #line default
            #line hidden
            this.Write(" entity = new ");
            
            #line 216 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 216 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.Name));
            
            #line default
            #line hidden
            this.Write("();\r\n\t\t\t\t//entity.Init();\r\n                entity._Id = System.Guid.NewGuid();\r\n\t" +
                    "\t\t\tentity.SetIsNew();\r\n\t\t\t\t//dao.AddItem<");
            
            #line 220 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 220 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.Name));
            
            #line default
            #line hidden
            this.Write(">(entity);\r\n                return entity;\r\n            }\r\n\t\t}\r\n\r\n\t\t");
            
            #line 225 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
}
            
            #line default
            #line hidden
            this.Write("        \r\n\t\t");
            
            #line 227 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic class Collections\r\n\t\t{\r\n\t\t\tprivate OfflineContext context;\r\n\r\n\t\t\tpubli" +
                    "c Collections(OfflineContext context)\r\n\t\t\t{\r\n\t\t\t\tthis.context = context;\r\n\t\t\t}\r\n" +
                    "\r\n\t\t\t");
            
            #line 238 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
 foreach(var entity in kvp.Value){ 
            
            #line default
            #line hidden
            this.Write(" \r\n\r\n\t\t\tpublic System.Collections.Generic.IEnumerable<");
            
            #line 240 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 240 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 240 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t{\r\n\t\t\t\tget \r\n\t\t\t\t{\r\n\t\t\t\t\treturn context.GetCollection<");
            
            #line 244 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 244 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write(">();\r\n\t\t\t\t}\r\n\t\t\t}\r\n\r\n\r\n\t\t\t");
            
            #line 249 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
 foreach(var tabularSection in entity.TabularSections){ 
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t\r\n\t\t\tpublic System.Collections.Generic.IEnumerable<");
            
            #line 251 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 251 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 251 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.Name));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 251 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 251 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.Name));
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t{\r\n\t\t\t\tget \r\n\t\t\t\t{\r\n\t\t\t\t\treturn context.GetCollection<");
            
            #line 255 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 255 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 255 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.Name));
            
            #line default
            #line hidden
            this.Write(">();\r\n\t\t\t\t}\r\n\t\t\t}\r\n\t\t\t\r\n\t\t\t");
            
            #line 259 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t");
            
            #line 261 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\r\n\t}\r\n\r\n\t");
            
            #line 266 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n\tpublic partial class OfflineContext : Microsoft.Synchronization.ClientServices" +
                    ".IsolatedStorage.IsolatedStorageOfflineContext \r\n\t{    \r\n        public const st" +
                    "ring SyncScopeName = \"");
            
            #line 270 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(config.ServerScope));
            
            #line default
            #line hidden
            this.Write(@""";
        
        public OfflineContext(string cachePath, System.Uri serviceUri) : 
                base(OfflineContext.GetSchema(), SyncScopeName, cachePath, serviceUri) {
        }
        
        public OfflineContext(string cachePath, System.Uri serviceUri, System.Security.Cryptography.SymmetricAlgorithm symmAlgorithm) : 
                base(OfflineContext.GetSchema(), SyncScopeName, cachePath, serviceUri, symmAlgorithm) {
        }

		");
            
            #line 280 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
 foreach(var kvp in config.EntitiesBySchema){ 
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\r\n\t\tprivate ");
            
            #line 282 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(kvp.Key));
            
            #line default
            #line hidden
            this.Write(".Collections _");
            
            #line 282 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(kvp.Key));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\tpublic ");
            
            #line 283 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(kvp.Key));
            
            #line default
            #line hidden
            this.Write(".Collections ");
            
            #line 283 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(kvp.Key));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            get\r\n            {\r\n                if (_");
            
            #line 287 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(kvp.Key));
            
            #line default
            #line hidden
            this.Write(" == null)\r\n                    _");
            
            #line 288 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(kvp.Key));
            
            #line default
            #line hidden
            this.Write(" = new ");
            
            #line 288 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(kvp.Key));
            
            #line default
            #line hidden
            this.Write(".Collections(this);\r\n                return _");
            
            #line 289 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(kvp.Key));
            
            #line default
            #line hidden
            this.Write(";\r\n            }\r\n        }\r\n\r\n\t\t");
            
            #line 293 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
}
            
            #line default
            #line hidden
            this.Write(@"


        private static Microsoft.Synchronization.ClientServices.IsolatedStorage.IsolatedStorageSchema GetSchema() 
		{
            Microsoft.Synchronization.ClientServices.IsolatedStorage.IsolatedStorageSchema schema = new Microsoft.Synchronization.ClientServices.IsolatedStorage.IsolatedStorageSchema();
			");
            
            #line 300 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
 foreach(var entity in config.Entities){ 
            
            #line default
            #line hidden
            this.Write("            schema.AddCollection<");
            
            #line 301 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 301 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write(">();\r\n\r\n\t\t\t");
            
            #line 303 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
 foreach(var tabularSection in entity.TabularSections){ 
            
            #line default
            #line hidden
            this.Write(" \r\n            schema.AddCollection<");
            
            #line 304 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 304 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 304 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabularSection.Name));
            
            #line default
            #line hidden
            this.Write(">();\r\n\t\t\t");
            
            #line 305 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t");
            
            #line 307 "D:\Projects\core\BitMobileServer\Core\CodeFactory\CodeGeneration\Templates\Code\Client.tt"
}
            
            #line default
            #line hidden
            this.Write("            return schema;\r\n        }\r\n    }\r\n\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public class ClientBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
